title: QT TRaining Services
description: All about QT in one place 
url: # you website url https://www.learnqt.guide/
baseurl: ''
favicon: /assets/blog/image/LearnQt.png
email: info@learntqt.guide
logo: /assets/blog/image/LearnQt.png

# for activate comment integration with github issue 
# need to install on repo visit https://github.com/apps/utterances - and click install
#githubrepo: rutura/learnqt

githubrepo: mesinkasir/mesinkasir.github.io

#navbar homepage slider version
navhome: 
 - name: Home
   link: '#'
 - name: Courses
   link: '#courses'
 - name: Book
   link: '#book'
 - name: About
   link: '#about'
 - name: Contact
   link: '#contact'
 - name: Blog
   link: '/blog/'

# navbar on page
navigation: 
 - name: Home
   link: /
 - name: Courses
   link: /courses
 - name: Books
   link: /books
 - name: About
   link: /about
 - name: Contact
   link: /contact
 - name: Blog
   link: /blog


# Course Links
coupon: 'STARTAUG2023'
couponvalidity: 'August 15,2023'
price: '$9.99'
pyside6widgetsbeginners : 'https://www.udemy.com/course/qt-for-python-pyside6-gui-for-beginners/?couponCode='
qt6guibeginners : 'https://www.udemy.com/course/qt6-c-gui-widgets-tutorial-for-beginners/?couponCode='
cpp20masterclass:  'https://www.udemy.com/course/the-modern-cpp-20-masterclass/?couponCode='
qtguibeginners: 'https://www.udemy.com/course/qt-c-gui-tutorial-for-complete-beginners/?couponCode='
qtguiintermediate: 'https://www.udemy.com/course/qt-c-gui-development-intermediate/?couponCode='
qmlbeginners: 'https://www.udemy.com/course/qt_quick_qml_tutorial_for_beginners/?couponCode='
qmlintermediate: 'https://www.udemy.com/course/interfacing-qt-quick-qml-to-cpp-intermediate/?couponCode='
qmladvanced: 'https://www.udemy.com/course/interfacing-qt-quick-qml-to-cpp-advanced/?couponCode='
multithreading: 'https://www.udemy.com/course/multi-threading-and-ipc-with-qt-c-plus-plus/?couponCode='

#footer area
footer: 
 logo: /assets/blog/image/LearnQt.png
 title: Learn QT
 content:  'Clear, Up Front Courses on Qt , We have made it our business to provide the best online learning resources for Qt Development.We put in the required effort to make sure the code resources coming with the courses are up to date and use the latest tools to reduce the husstle for students as much as possible. We already have the basic courses on Qt C++ and QML out and there are more in the pipeline.'
 icon: /assets/img/learnqt-nav.webp
 button: Become a Pro Member
 link: /premium/

#social media
youtube: https://www.youtube.com/channel/UCUYUFiuJ5XZ3JYtbq5dXRKQ
facebook: https://web.facebook.com/learnqtguide/
twitter: https://twitter.com/learnqtguide
linked: https://www.linkedin.com/in/daniel-gakwaya-2a570092

#author
author: 
 title: Your Instructor Author and Mentor
 image: /assets/img/daniel.webp
 name: Daniel Haghwa
 label: Udemy Instructor Patner
 description: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. 

# copyrights
footercopyrights: copyrights 2023 learnqtguides.com all rights reserved

# blog post pagination
paginate: 3
# default blog post
paginate_path: "/blog/page:num/"


# settup

collections:
  courses:
    output: true
  books:
    output: true
  pages:
    output: true
defaults:
  - scope:
      path: ""
      type: "courses"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "books"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
#      permalink: /:year/:month/:title:output_ext
      permalink: /:title
  - scope:
      path: ""
    values:
      layout: "default"
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

markdown: kramdown
highlighter: rouge
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class   : 'syntax'